# -*- coding: utf-8 -*-
"""QR Code Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p5HPfEdOySgXUh8ty-U1C72SGnqz5_t6
"""

!pip install pyqrcode

import pyqrcode
from pyqrcode import QRCode

# String which represent the QR code
#s = "https://thecleverprogrammer.com/2021/01/09/qr-codes-with-python/"

s = input("Paste the link: ")

# Generate QR code
url = pyqrcode.create(s)

# Create and save the png file naming "myqr.png"
url.svg("myqrcode.svg", scale=8)